FROM nginx:1.19
COPY aquiletour2021/dockers/httprouter/nginx.conf /etc/nginx/nginx.conf
COPY certificate/fbb556b375ecbfdc.crt /etc/ssl/certs/fbb556b375ecbfdc.crt
COPY certificate/aiguilleurca.key /etc/ssl/private/aiguilleurca.key
