FROM nginx:1.19
COPY aquiletour2021/dockers/httprouter/nginx.conf /etc/nginx/nginx.conf
COPY certificate/d706a8e1929c0867.crt /etc/ssl/certs/d706a8e1929c0867.crt
COPY certificate/aiguilleurca.key /etc/ssl/private/aiguilleurca.key
